const config = {
  types: [
    { value: 'feat', name: 'feat:     A new feature' },
    { value: 'fix', name: 'fix:      A bug fix' },
    { value: 'docs', name: 'docs:     Documentation only changes' },
    { value: 'style', name: 'style:    Changes that do not affect the meaning of the code' },
    {
      value: 'refactor',
      name: 'refactor: A code change that neither fixes a bug nor adds a feature',
    },
    { value: 'perf', name: 'perf:     A code change that improves performance' },
    { value: 'test', name: 'test:     Adding missing tests or correcting existing tests' },
    {
      value: 'build',
      name: 'build:    Changes that affect the build system or external dependencies',
    },
    { value: 'ci', name: 'ci:       Changes to our CI configuration files and scripts' },
    { value: 'chore', name: 'chore:    Other changes that do not modify src or test files' },
    { value: 'revert', name: 'revert:   Reverts a previous commit' },
  ],
  scopes: [
    { name: 'dashboard' },
    { name: 'tools' },
    { name: 'results-cleaner' },
    { name: 'file-uploader' },
    { name: 'table' },
    { name: 'parser' },
    { name: 'storage' },
    { name: 'auth' },
    { name: 'ui' },
    { name: 'hooks' },
    { name: 'docs' },
    { name: 'e2e' },
    { name: 'tests' },
    { name: 'config' },
    { name: 'deps' },
    { name: 'ci' },
  ],
  appendBranchNameToCommitMessage: false,
  allowTicketNumber: false,
  isTicketNumberRequired: false,
  ticketNumberPrefix: 'TICKET-',
  ticketNumberRegExp: '\\d+',
  appendTicketNumberToCommitMessage: false,
  isSubjectEmptyRequired: false,
  subjectLimit: 100,
  subjectPattern: '^[A-Z].*',
  subjectPatternErrorMsg: 'subject must start with a capital letter',
  emptyScopesSufixLength: 0,
  maxSubjectLength: 100,
  minSubjectLength: 30,
  maxBodyLength: 100,
  messages: {
    type: "Select the type of change that you're committing:",
    scope: '\nDenote the SCOPE of this change (optional):',
    customScope: 'Denote the SCOPE of this change:',
    subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
    body: 'Provide a LONGER description of the change (optional). Use | to break new line:',
    breaking: 'List any BREAKING CHANGES (optional):',
    footer: 'List any ISSUES CLOSED by this change (optional). E.g.: #31, #34:',
    confirmCommit: 'Are you sure you want to proceed with the commit above?',
  },
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix'],
  footerPrefix: '',
  askForBreakingChangeFirst: true,
};

export default config;
