#!/usr/bin/env sh
. "$(dirname "$0")/h"

echo "🔍 Running lint..."
npm run lint-staged || exit 1

echo "🔍 Running type check..."
npm run type-check || exit 1

echo "🔍 Running all tests concurrently..."
npm run test:all || exit 1